# Generated by Django 6.0.6 on 2026-06-17 18:55

import authlib.oauth2.rfc6749.models
import django.db.models.deletion
import openbrain.oauth.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('client_id', models.CharField(max_length=48)),
                ('redirect_uri', models.TextField(blank=True, default='')),
                ('response_type', models.TextField(blank=True, default='')),
                ('scope', models.TextField(blank=True, default='')),
                ('auth_time', models.IntegerField(default=openbrain.oauth.models._now_epoch)),
                ('code_challenge', models.TextField(blank=True, null=True)),
                ('code_challenge_method', models.CharField(blank=True, max_length=48, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_codes', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(authlib.oauth2.rfc6749.models.AuthorizationCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=48, unique=True)),
                ('client_secret', models.CharField(blank=True, default='', max_length=120)),
                ('client_id_issued_at', models.IntegerField(default=0)),
                ('client_secret_expires_at', models.IntegerField(default=0)),
                ('client_metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_clients', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(authlib.oauth2.rfc6749.models.ClientMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=48)),
                ('token_type', models.CharField(default='Bearer', max_length=40)),
                ('access_token', models.TextField()),
                ('refresh_token', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('scope', models.TextField(blank=True, default='')),
                ('issued_at', models.IntegerField(default=openbrain.oauth.models._now_epoch)),
                ('access_token_revoked_at', models.IntegerField(default=0)),
                ('refresh_token_revoked_at', models.IntegerField(default=0)),
                ('expires_in', models.IntegerField(default=0)),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('sub', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(authlib.oauth2.rfc6749.models.TokenMixin, models.Model),
        ),
    ]
