# Generated by Django 6.0.6 on 2026-06-17 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=48)),
                ('revoked_after', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_revocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_revocation',
                'constraints': [models.UniqueConstraint(fields=('user', 'client_id'), name='oauth_revocation_user_client_uniq')],
            },
        ),
    ]
